### ISSUE TITLE
please update export-director-metadata to work with cred hub

### ISSUE THREAD

**Issue by eodchop** [pivotal-cf/bbr-pcf-pipeline-tasks#3] opened 2017-10-25 20:13 UTC
Hello, 
we have an issue where export-director-metadata is not working with ERT where credhub is enabled.
error below
bosh director unreachable or unhealthy: Fetching info: Performing request GET 'https://<redacted_ip>:25555/info': Performing GET request: Retry: Get https://<redacted_ip>:25555/info: Forbidden

**Comment by alamages** [comment] 2018-05-09 09:34
What version of PCF are you using? 
We are running the tasks against a PCF 2.1 environment in our pipeline successfully. 
Can you please provide more details on the issue so we can reproduce it?

cc @jamesjoshuahill

**Comment by ChunyiLyu** [comment] 2018-05-21 14:12
We tried to reproduce the error by testing against PCF 1.12, which comes with credhub enabled on the director. Both ert-backup and director-backup have succeeded. We will close this issue now since we can't reproduce the same failure. Feel free to reopen or create new issues with more details.

Cheers,
Chunyi && @alamages

**Closed as completed** 2018-05-21 14:12 UTC
Labels: accepted
